### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by sshadmand** [lmorchard/arboretum#1]
Hey, I am working on creating an outliner myself. Saw yours and would like to contribute. Had a problem building though ... 
# > gulp build

```
    throw er; // Unhandled 'error' event
      ^

SyntaxError: /Users/sshadmand/Downloads/arboretum-master/src/index.js: Unexpected token (80:0)
  78 |     </Router>
  79 |   </Provider>,
> 80 | ), document.getElementById('app'));
     | ^
  81 | 
    at Parser.pp.raise (/Users/sshadmand/Downloads/arboretum-master/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/sshadmand/Downloads/arboretum-master/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.parseParenAndDistinguishExpression (/Users/sshadmand/Downloads/arboretum-master/node_modules/babylon/lib/parser/expression.js:623:32)
    at Parser.pp.parseExprAtom (/Users/sshadmand/Downloads/arboretum-master/node_modules/babylon/lib/parser/expression.js:471:19)
    at Parser.parseExprAtom (/Users/sshadmand/Downloads/arboretum-master/node_modules/babylon/lib/plugins/jsx/index.js:16:22)
    at Parser.pp.parseExprSubscripts (/Users/sshadmand/Downloads/arboretum-master/node_modules/babylon/lib/parser/expression.js:270:19)
    at Parser.pp.parseMaybeUnary (/Users/sshadmand/Downloads/arboretum-master/node_modules/babylon/lib/parser/expression.js:250:19)
    at Parser.pp.parseExprOps (/Users/sshadmand/Downloads/arboretum-master/node_modules/babylon/lib/parser/expression.js:180:19)
    at Parser.pp.parseMaybeConditional (/Users/sshadmand/Downloads/arboretum-master/node_modules/babylon/lib/parser/expression.js:157:19)
    at Parser.pp.parseMaybeAssign (/Users/sshadmand/Downloads/arboretum-master/node_modules/babylon/lib/parser/expression.js:120:19)
sshadmand(B) ~/Downloads/arboretum-master #> 

```

**Comment by sshadmand** [comment]
Fixed: https://github.com/lmorchard/arboretum/pull/2
